title:             Valera – Free Bootstrap Theme
email:             your-email@example.com
description: ""
author: ""

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - LICENSE
  - README.md
  - valera.gif

# Social Profiles
twitter_username: ""
github_username: ""
facebook_username: ""
